


#homo
seq1 = 'MEDFEKIEKIGEGTYGVVYKGRNRLTGQIVAMKKIRLESDDEGVPSTAIREISLLKELKHENIVCLEDVLMEENRIYLIFEFLSMDLKKYMDSLPVDKHMESELVRSYLYQITSAILFCHRRRVLHRDLKPQNLLIDKSGLIKVADFGLGRSFGIPVRIYTHEIVTLWYRAPEVLLGSPRYSCPVDIWSIGCIFAEMATRKPLFQGDSEIDQLFRMFRILKTPTEDIWPGVTSLPDYKNTFPCWSTNQLTNQLKNLDANGIDLIQKMLIYDPVHRISAKDILEHPYFNGFQSGLVRN'


#bos taurus
seq2 ='MEDYTKIEKIGEGTYGVVYKGRHKTTGQVVAMKKIRLESEEEGVPSTAIREISLLKELRHPNIVSLQDVLMQDSRLYLIFEFLSMDLKKYLDSIPPGQYMDSSLVKSYLYQILQGIVFCHSRRVLHRDLKPQNLLIDDKGTIKLADFGLARAFGIPIRVYTHEVVTLWYRSPEVLLGSARYSTPVDIWSIGTIFAELATKKPLFHGDSEIDQLFRIFRALGTPNNEVWPEVESLQDYKNTFPKWKPGSLASHVKNLDENGLDLLSKMLIYDPAKRISGKMALNHPYFNDLDNQIKKM'

lengte_1 = len(seq1)
lengte_2 = len(seq2)

score = 0

for x, y in zip(seq1, seq2):
    if x == y:
        score +=1

print(score)

gemiddelde_lengte = (lengte_1 + lengte_2 / 100)
print(gemiddelde_lengte)

identity_percentage = (score / gemiddelde_lengte * 100)
print('Dit is het identity percentage.: ' ,identity_percentage)

